[workspace]
resolver = "2"
members = [
    "crates/shaahid",
    "crates/shaahid-contract",
    "crates/shaahid-governance",
]

[workspace.package]
version = "0.1.3"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tacticaldoll/shaahid"
publish = true

[workspace.dependencies]
shaahid-contract = { path = "crates/shaahid-contract", version = "0.1.3" }
tianheng = "0.3.0"
